
name: Conda package

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up and activate Conda environment
        uses: conda-incubator/setup-miniconda@v3
        
      - name: Verify conda environment
        run: conda env list

      - name: Install Conda package build tools
        run: |
          conda config --append channels conda-forge
          conda install conda-build conda-forge-pinning

      - name: Detect VS path and set up VS C/C++ environment
        shell: cmd
        run: |
          for /f "delims=" %%i in ('vswhere -products * ^| findstr "installationPath: "') do set VS_INSTALL_DIR=%%i
          set "VS_INSTALL_DIR=%VS_INSTALL_DIR:installationPath: =%"
          call "%VS_INSTALL_DIR%\VC\Auxiliary\Build\vcvars64.bat"

          
      - name: Build test package
        run: conda-build .conda\recipe\

      - name: Install test package
        run: conda install C:\Miniconda\envs\test\conda-bld\win-64\print-test-1.0.0-h82bb817_0.conda

      - name: Run custom package
        run: print-test
          

