# This is a basic workflow to help you get started with Actions

name: Conda package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          architecture: x64  # Or x86 if you need 32-bit

      - name: Setup vcvars for cl.exe
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
 
      - name: Conda set up
        uses: conda-incubator/setup-miniconda@v3

      - name: Verify conda environment
        run: |
          conda env list

      - name: Install conda-build
        run: |
          conda config --append channels conda-forge
          conda install conda-build conda-forge-pinning vs2022_win-64

      - name: Build test package
        run: |
          conda-build .conda\recipe\

