name: Conda package

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:          

    - name: Set
      shell: cmd
      run: |
        set PKG=Test
        echo PKG_NAME=%PKG% >> "%GITHUB_ENV%"

    - name: Get
      run: echo "${{ env.PKG_NAME }}"
          

